### ISSUE TITLE
Environment Detection Causing Errors In Browser

### ISSUE THREAD

**Issue by nruhe** [kripken/ammo.js#109]
Hello. 

I'm trying to utilize this library alongside ES6 modules, via SystemJS. The problem is that the Ammo library seems to be doing environment detection based on whether CommonJS support is defined. Browsers can support CommonJS style formatting, so I'm running into a problem with Ammo trying to request a file at  "/path" and "/fs".

The library shouldn't assume FS and Path modules are available just because CommonJS syntax is available. I'd appreciate it if you wouldn't mind fixing this when you get the chance. If I get frustrated enough in the meantime, I'll probably make a pull request, though I think I've got a work around.

Thanks!

-Nick

**Comment by nruhe** [comment]
Realized the problem is with Emscripten, not Ammo.

**Comment by agilgur5** [comment]
@nruhe how did you end up fixing this problem for your use case?

**Comment by agilgur5** [comment]
@kripken is there a way to use MEMFS instead of NODEFS (the problem seems to be that the Emscripten build is using NODEFS due to it detecting CommonJS listed above)?

Is there an argument I can pass to Ammo to do that? Or would I have edit the Ammo script and/or recompile a different way with Emscripten so it always uses MEMFS?

**Comment by kripken** [comment]
Emscripten programs will not use NODEFS automatically - it must be explicitly set up. So ammo.js must be using MEMFS.

Something else must be going wrong, it would be good to reduce this to a testcase and file on the emscripten bug tracker.
