### ISSUE TITLE
Up-to-date benchmarks for Ammo vs Bullet?

### ISSUE THREAD

**Issue by josephrocca** [kripken/ammo.js#119]
Are there are any up-to-date benchmarks comparing the performance of Ammo and Bullet? I know some work is being done on benchmarking Ammo and other JS libraries, but it'd be great to see how it's going against Bullet too.

**Comment by kripken** [comment]
Sure, take a look at http://arewefastyet.com/#machine=28&view=breakdown&suite=asmjs-apps , at bullet-throughput. Firefox is around 2x slower, Chrome is around 3.5x.

Note that those numbers are without float32 optimizations, which would make Firefox a little faster.

**Comment by josephrocca** [comment]
Neat! This is very handy, thanks. Can I ask: are there (in your knowledge/opinion) any bottlenecks that would stop Ammo from getting to, say, 90% of Bullet's speed? Bottlenecks in terms of asm or emscripten, that is.

**Comment by kripken** [comment]
One thing is that ammo.js is sandboxed, like everything on the web, which definitely adds some 20-30% overhead.

Another is that native Bullet can be autovectorized. SIMD support is coming to browsers, but isn't quite there yet. Math-heavy code like Bullet can often benefit from autovectorization.

Aside from that, there shouldn't be much in the way. There's probably some additional performance gap due to native compilers being much older and more mature than JS VMs, but that gap is shrinking all the time.

**Comment by josephrocca** [comment]
Okay, so from your comments it sounds like 80% is about as close as we'll get in the foreseeable future. That's pretty good by standards. Thanks for your help :)

**Comment by VladislavAnkudinov** [comment]
Hi there! Quite a bit time has passed since 2015. Any updates on the topic? The link given at beginning of the talk seem broken (http://arewefastyet.com/#machine=28&view=breakdown&suite=asmjs-apps)

**Comment by kripken** [comment]
The emscripten benchmark suite has bullet it in. You can run `python3 tests/runner.py benchmark.test_zzz_bullet` to test it, after editing `tests/test_benchmark.py` to pick which compilers you want to compare (see the list of `benchmarkers`).
