### ISSUE TITLE
Possible implementation to A-Frame for complex 3D meshes

### ISSUE THREAD

**Issue by h0r0man** [kripken/ammo.js#143]
Hello, in the year of VR, currently [A-Frame](https://github.com/aframevr/aframe/) project for WebVR doesn’t have any solid physics implementation, there’s a third-part integrations but all with limitations for complex 3D mesh, so currently how behaves ammo.js with a complex 3d meshes?

**Comment by willeastcott** [comment]
It works fine. I use it to create btBvhTriangleMeshShape objects in PlayCanvas. The only problem is that creation is quite slow because you have to add triangles individually:

https://github.com/playcanvas/engine/blob/master/src/framework/components/collision/system.js#L456

IIRC, it's because the Bullet function that allows you to pass in arbitrary arrays of triangles isn't exposed in Ammo.
