### ISSUE TITLE
Question: Memory Management

### ISSUE THREAD

**Issue by sbi-krisj** [kripken/ammo.js#236]
Amazing library and porting work!

I’m using the default 64MB total memory without growth and have a couple questions:

1. Is there a function or variable to determine the current stack pointer (offset into HEAP8)?
2. Is there a best practice for completely reinitializing Ammo, memory usage and all? After running my simulation multiple times, I eventually run out of memory.  Here's what I'm currently calling between each simulation:

```
Ammo.destroy(this.world);
Ammo.destroy(this.solver);
Ammo.destroy(this.broadphase);
Ammo.destroy(this.dispatcher);
Ammo.destroy(this.collisionConfiguration);
```

Thank you!

**Comment by kripken** [comment]
Emscripten has stackSave/stackRestore to get and set the stack pointer. Those may not be exported by default in ammo, though, so may need to rebuild with that.

Best to create a new ammo instance for reinitializing - otherwise you can get memory fragmentation issues that are common with malloc/free. The current JS we emit will instantiate once, but you could wrap the entire thing in another function for multiple instantiations.
